sylius_grid:
    grids:
        # config grid pour les marques
        app_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Brand
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                description:
                    type: string
                    label: sylius.ui.description
                createdAt:
                    type: datetime
                    label: Date création
                    options:
                        format: 'd/m/Y' 
                updatedAt:
                    type: datetime
                    label: Date modification
                    options:
                        format: 'd/m/Y' 
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
               