app_admin_brand:
    resource: |
        alias: app.brand
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: app_admin_brand
        vars:
            all:
                subheader: app.ui.brand # define a translation key for your entity subheader
            index:
                icon: 'file image outline' # choose an icon that will be displayed next to the subheader
    type: sylius.resource
    prefix: admin

app_admin_brand_products:
    path: /admin/brands/{id}/products
    methods: [GET]
    defaults:
        _controller: App\Controller\BrandController
        _sylius:
            template: brand/index.html.twig
            repository:
                method: findProductsbyBrand
                arguments:
                   - "expr:service('sylius.context.brand').getBrand()"
